# Generated by Django 5.0 on 2024-05-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stayintouch',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
