# Generated by Django 5.0.2 on 2024-02-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_is_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinformation',
            name='product_image',
        ),
    ]
