# Generated by Django 5.0 on 2024-03-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_register_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_profile',
            field=models.ImageField(default='user_profile/default.webp', upload_to='user_profile/'),
        ),
    ]
